version: "3.8"

services:
  webapp:
    image: nginx:latest
    container_name: webapp
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./webapp/html:/usr/share/nginx/html:ro
      - ./webapp/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webapp/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - monitoring-network

  # Log generator for testing
  log-generator:
    image: busybox
    container_name: log-generator
    depends_on:
      - webapp
    command: >
      sh -c "while true; do 
             wget -q -O /dev/null http://webapp/not-found-page || true; 
             sleep 30; 
             done"
    restart: unless-stopped
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge
