apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s
      httpMethod: GET
    version: 1

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    jsonData:
      maxLines: 1000
