server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*[^|]))
          source: tag
      - labels:
          container_name:

  - job_name: webapp_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: webapp
          app: nginx
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      - regex:
          expression: ".*(?P<level>error|Error|ERROR|warn|Warn|WARNING).*"
      - labels:
          level:
      - metrics:
          error_count:
            type: Counter
            description: "Count of error logs"
            source: level
            config:
              action: inc
              match_all: true
