server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - { { STACK_HOSTNAME } }
        labels:
          job: docker
          host: { { STACK_HOSTNAME } }
          __path__: /var/lib/docker/containers/*/*-json.log

  # NGINX error logs with explicit configuration
  - job_name: nginx_error_logs
    static_configs:
      - targets:
          - { { STACK_HOSTNAME } }
        labels:
          job: webapp
          app: nginx
          host: { { STACK_HOSTNAME } }
          log_type: error
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      # Add hostname label to help identify logs
      - static_labels:
          hostname: { { STACK_HOSTNAME } }
